name: Bhavit Desai
favicon: null
layout_spectrum: 0.087532993638888
typography_spectrum: 0.22553661512210965
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.23806825373321772
  lightness: 0.42137139989063144
  saturation: 0.11780524905771017
  rhythmicContrast: 0.01118798996321857
purpose: []
